image: nativecode/deno-build:0.1.0

stages:
  - test
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - deno install --allow-net --name status-check status-check/mod_run.ts
  - deno install --allow-run --name dent dent/run.ts

.configure-publish:
  stage: publish
  artifacts:
    paths:
      - dist
  before_script:
    - mkdir dist
    - source .ci-env.sh
    - bash .citools/setup-git ${BUILD_REPO_BRANCH} ${BUILD_REPO_GIT} ${BUILD_REPO_EMAIL}
    - bash .citools/setup-ssh ${BUILD_REPO_DOMAIN} ${BUILD_REPO_SSHKEY_PATH} ${BUILD_REPO_DOMAIN_SSH}
  after_script:
    - git push origin --tags

test:
  stage: test
  script:
    - status-check //localhost:5672 //localhost:6379 http://localhost:5984
    - deno run --allow-env --allow-read --allow-write --unstable dent-cli/mod_run.ts refresh --log
    - deno test -c tsconfig.json --allow-env --allow-read --allow-net --allow-write --unstable
  after_script:
    - deno run --allow-run dent/mod.ts -- commit-parser
  services:
    - couchdb:2
    - rabbitmq:3-management-alpine
    - redis:6-alpine
  variables:
    COUCHDB_USER: guest
    COUCHDB_PASSWORD: guest
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

prerelease:
  extends: .configure-publish
  script:
    - deno bundle -c tsconfig.json --unstable mod.ts dist/mod.ts
    - dent tag-release
  only:
    - develop

release:
  extends: .configure-publish
  script:
    - deno bundle -c tsconfig.json --unstable mod.ts dist/mod.ts
    - dent tag-release
  only:
    - master
