image: nativecode/deno:0.2.0

stages:
  - test
  - publish

test:
  stage: test
  script:
    - deno test --allow-env --allow-read

publish:
  stage: publish
  script:
    - mkdir dist
    - deno bundle mod.ts dist/mod.ts
  only:
    - master
  artifacts:
    paths:
      - dist
