image: nativecode/deno:0.2.0

stages:
  - test
  - publish

test:
  stage: test
  script:
    - deno run --allow-net status-check/mod_run.ts //localhost:5672 //localhost:6379 http://localhost:5984
    - deno run --allow-env --allow-read --allow-write --unstable dent-cli/mod_run.ts refresh --log
    - deno test -c tsconfig.json --allow-env --allow-read --allow-net --allow-write --unstable
  services:
    - couchdb:2
    - rabbitmq:3-management-alpine
    - redis:6-alpine
  variables:
    COUCHDB_USER: guest
    COUCHDB_PASSWORD: guest
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

publish:
  stage: publish
  script:
    - mkdir dist
    - deno bundle -c tsconfig.json --unstable mod.ts dist/mod.ts
  only:
    - master
  artifacts:
    paths:
      - dist
