image: nativecode/deno-build:0.1.0

stages:
  - test
  - publish

test:
  stage: test
  script:
    - deno run --allow-net status-check/mod_run.ts //localhost:5672 //localhost:6379 http://localhost:5984
    - deno run --allow-env --allow-read --allow-write --unstable dent-cli/mod_run.ts refresh --log
    - deno test -c tsconfig.json --allow-env --allow-read --allow-net --allow-write --unstable
  services:
    - couchdb:2
    - rabbitmq:3-management-alpine
    - redis:6-alpine
  variables:
    COUCHDB_USER: guest
    COUCHDB_PASSWORD: guest
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

prerelease:
  stage: publish
  script:
    - git config --global user.email "opensource@nativecode.com"
    - git config --global user.name "NativeCode Builder"
    - git checkout develop
    - mkdir dist
    - deno bundle -c tsconfig.json --unstable mod.ts dist/mod.ts
    - npx standard-version
    - git push --follow-tags origin develop
  only:
    - develop
  artifacts:
    paths:
      - dist

release:
  stage: publish
  script:
    - git config --global user.email "opensource@nativecode.com"
    - git config --global user.name "NativeCode Builder"
    - git checkout master
    - mkdir dist
    - deno bundle -c tsconfig.json --unstable mod.ts dist/mod.ts
    - npx standard-version
    - git push --follow-tags origin master
  only:
    - master
  artifacts:
    paths:
      - dist
