image: alpine:latest

stages:
  - build

before_script:
  - apk add curl
  - curl -fsSL https://deno.land/x/install/install.sh | sh

continuous:
  stage: build
  script:
    - export DENO_INSTALL="/root/.deno"
    - export DENO_DIR="$DENO_INSTALL/.cache"
    - export PATH="$DENO_INSTALL/bin:$PATH"
    - deno test
